/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttsh.ifhaam.view.constraintpanels;


import com.ttsh.ifhaam.controller.TimeTableManager;
import com.ttsh.ifhaam.models.Constraints.Constraint;
import com.ttsh.ifhaam.models.Constraints.SubjectNotThisDay;
import com.ttsh.ifhaam.models.Exam;
import com.ttsh.ifhaam.models.Subject;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
/**
 *
 * @author Ahmed
 */
public class SubjectNotThisDayPan extends javax.swing.JPanel implements ConstraintValueater{
    Constraint con;
    ArrayList<Exam> exams;
    /**
     * Creates new form SubjectNotThisDayPan
     */
    public SubjectNotThisDayPan() {
        initComponents();
        exams = TimeTableManager.getInstance().getExams();
        for(Exam exam :exams){
            for(Subject sbj: exam.getSubjects()){
                cmbSubjct.addItem(sbj);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpDate = new org.jdesktop.swingx.JXDatePicker();
        spnDate = new javax.swing.JSpinner();
        spnFitness = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        cmbSubjct = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dpDate1 = new org.jdesktop.swingx.JXDatePicker();
        spnDate1 = new javax.swing.JSpinner();
        spnFitness1 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();

        dpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDateActionPerformed(evt);
            }
        });

        spnDate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnDateStateChanged(evt);
            }
        });

        jLabel3.setText("Fitness");

        jLabel1.setText("Subject");

        jLabel2.setText("Date to avoid ");

        dpDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpDate1ActionPerformed(evt);
            }
        });

        spnDate1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnDate1StateChanged(evt);
            }
        });

        spnFitness1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel4.setText("Fitness");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbSubjct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spnFitness1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(dpDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSubjct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnFitness1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDateActionPerformed
        // TODO add your handling code here:
        Date[] dates =TimeTableManager.getInstance().getDates();

        if(!(
            (dpDate.equals(dates[0])) ||
            (dpDate.getDate().after(dates[0] ) && dpDate.getDate().before(dates[dates.length-1])) ||
            (dpDate.equals(dates[dates.length-1]))

        )){

            dpDate.setDate(dates[0]);
            JOptionPane.showMessageDialog(this,"Date Selected is out of the date limit selecting the first day", "Invaliid"
                ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_dpDateActionPerformed

    private void spnDateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnDateStateChanged
        // TODO add your handling code here:
        if(evt.getSource().equals(spnDate)){
            try{
                dpDate.setDate(TimeTableManager.getInstance().getDates()[(int)spnDate.getValue()-1] );

            }catch(Exception ex){

                JOptionPane.showMessageDialog(null,"Invalid Input"+ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                spnDate.setValue(1);

            }
        }
    }//GEN-LAST:event_spnDateStateChanged

    private void spnDate1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnDate1StateChanged
        // TODO add your handling code here:
        if(evt.getSource().equals(spnDate)){
            try{
                dpDate1.setDate(TimeTableManager.getInstance().getDates()[(int)spnDate.getValue()-1] );

            }catch(Exception ex){

                JOptionPane.showMessageDialog(null,"Invalid Input"+ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
                spnDate.setValue(1);

            }
        }
    }//GEN-LAST:event_spnDate1StateChanged

    private void dpDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpDate1ActionPerformed
        // TODO add your handling code here:
        Date[] dates =TimeTableManager.getInstance().getDates();

        if(!(
            (dpDate1.equals(dates[0])) ||
            (dpDate1.getDate().after(dates[0] ) && dpDate1.getDate().before(dates[dates.length-1])) ||
            (dpDate1.equals(dates[dates.length-1]))

        )){

            dpDate.setDate(dates[0]);
            JOptionPane.showMessageDialog(this,"Date Selected is out of the date limit selecting the first day", "Invaliid"
                ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_dpDate1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Subject> cmbSubjct;
    private org.jdesktop.swingx.JXDatePicker dpDate;
    private org.jdesktop.swingx.JXDatePicker dpDate1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spnDate;
    private javax.swing.JSpinner spnDate1;
    private javax.swing.JSpinner spnFitness;
    private javax.swing.JSpinner spnFitness1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Constraint getConstraint() throws ConstraintException {
       Date date = dpDate1.getDate();
       int fitness = (int) spnFitness1.getValue();
       Subject subject = (Subject) cmbSubjct.getSelectedItem();
       con = new SubjectNotThisDay(fitness,subject,date);
       return con;
    }
}
