/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttsh.ifhaam.view;

import com.ttsh.ifhaam.controller.TimeTableManager;
import com.ttsh.ifhaam.models.Constraints.ClassRoomWhileClassRoomConstraint;
import com.ttsh.ifhaam.models.Constraints.Constraint;
import com.ttsh.ifhaam.models.Constraints.SubjectGap;
import com.ttsh.ifhaam.view.constraintpanels.ConstraintException;
import com.ttsh.ifhaam.view.constraintpanels.ConstraintValueater;
import com.ttsh.ifhaam.view.constraintpanels.SubjectBeforePan;
import com.ttsh.ifhaam.view.constraintpanels.SubjectNotThisDayPan;
import com.ttsh.ifhaam.view.constraintpanels.SubjectSubjectGapPan;
import com.ttsh.ifhaam.view.constraintpanels.TwoClassRoom;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ahmed
 */
public class ConstraintsManager extends javax.swing.JFrame {
    public static String[] CONSTRAINTTYPES = {"One of Two Room","Subject Before","Gap Between Subjects","Subject not this Day"};
    ConstraintValueater valueater;
    /**
     * Creates new form ConstraintsManager
     */
    public ConstraintsManager() {
        initComponents();
        loadConstraints();
        constraintSelector.setListData(CONSTRAINTTYPES);
    }
    
    private void loadConstraints(){
        ArrayList<Constraint> constraints = TimeTableManager.getInstance().getConstraints();
        DefaultListModel model  = ((DefaultListModel)jList1.getModel());
        model.removeAllElements();
        for(Constraint con :constraints){
            model.addElement(con);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        constraintSelector = new javax.swing.JList<>();
        constraintPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        constraintSelector.setBorder(new javax.swing.border.MatteBorder(null));
        constraintSelector.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        constraintSelector.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                constraintSelectorValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(constraintSelector);

        constraintPanel.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout constraintPanelLayout = new javax.swing.GroupLayout(constraintPanel);
        constraintPanel.setLayout(constraintPanelLayout);
        constraintPanelLayout.setHorizontalGroup(
            constraintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        constraintPanelLayout.setVerticalGroup(
            constraintPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jButton1.setText("Add Constraints");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setModel(new DefaultListModel<Constraint>());
        jScrollPane2.setViewportView(jList1);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(constraintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(constraintPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void constraintSelectorValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_constraintSelectorValueChanged
        // TODO add your handling code here:
        if(!evt.getValueIsAdjusting()){
            System.out.println("Selection");
            switch(constraintSelector.getSelectedIndex()){
                case 0:
                    System.out.println("case 0");
                    //constraintPanel.removeAll();
                    //constraintPanel.setLayout(new BorderLayout());
                    valueater =  new TwoClassRoom();
                    //constraintPanel.add((JPanel)valueater,BorderLayout.CENTER);
                    break;
                    
                case 1:
                    System.out.println("case 1");
                    //constraintPanel.removeAll();
                    //constraintPanel.setLayout(new BorderLayout());
                    valueater = new SubjectBeforePan();
                    //constraintPanel.add((JPanel)valueater,BorderLayout.CENTER);
                    break;
                    
                    
                case 2:
                    System.out.println("case 2");
                    valueater = new SubjectSubjectGapPan();
                    break;
                    
                case 3:
                    System.out.println("case 3");
                    valueater = new SubjectNotThisDayPan();
                    break;
                    
                default :
                    System.out.println("default");
                    valueater = new TwoClassRoom();
                    break;
                    
            }
            constraintPanel.removeAll();
            constraintPanel.setLayout(new BorderLayout());
            constraintPanel.add((JPanel)valueater,BorderLayout.CENTER);
            this.pack();
            this.repaint();
        }
    }//GEN-LAST:event_constraintSelectorValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Constraint con = valueater.getConstraint();
            TimeTableManager.getInstance().addConstraint(con);
            loadConstraints();
        }catch(ConstraintException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1.getSelectedIndex();
        
        if(selectedIndex!=-1){
            TimeTableManager.getInstance().getConstraints().remove(selectedIndex);
            loadConstraints();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstraintsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstraintsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstraintsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstraintsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstraintsManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel constraintPanel;
    private javax.swing.JList<String> constraintSelector;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList<Constraint> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
