/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttsh.ifhaam.view;

import com.ttsh.ifhaam.controller.Algorithm;
import com.ttsh.ifhaam.controller.DataBaseController;
import com.ttsh.ifhaam.controller.TimeTableManager;
import com.ttsh.ifhaam.models.ClassRoom;
import com.ttsh.ifhaam.models.ClassRoomListCellRenderer;
import com.ttsh.ifhaam.models.NoBFSException;
import com.ttsh.ifhaam.models.Population;
import java.awt.Color;
import java.awt.event.ActionEvent;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.SwingWorker;


/**
 *
 * @author Ahmed
 */
public class Initializing extends javax.swing.JFrame {
    ArrayList<ClassRoom> classRooms;
    /**
     * Creates new form Initializing
     */
    public Initializing() {
        initComponents();
        refreshClassRooms();
        selectedClassRoomsList.setCellRenderer(new ClassRoomListCellRenderer());
        classRoomsList.setCellRenderer(new ClassRoomListCellRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnLoadClassRooms = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        classRoomsList = new javax.swing.JList<ClassRoom>();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedClassRoomsList = new javax.swing.JList<>();
        btnAddAll = new javax.swing.JButton();
        btnAddSelected = new javax.swing.JButton();
        btnRemoveSelected = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDaysCount = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        timeSlotsList = new javax.swing.JList<>();
        txtTimeSlotEnter = new javax.swing.JTextField();
        btnTimeslotAdd = new javax.swing.JButton();
        btnRemoveTimeSlot = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        prgProcess = new javax.swing.JProgressBar();
        lblProcessStatus = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select class rooms"));

        btnLoadClassRooms.setText("Refresh");
        btnLoadClassRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadClassRoomsActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(classRoomsList);

        jScrollPane2.setViewportView(selectedClassRoomsList);

        btnAddAll.setText(">>");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });

        btnAddSelected.setText(">");
        btnAddSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSelectedActionPerformed(evt);
            }
        });

        btnRemoveSelected.setText("Remove Selected");
        btnRemoveSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveSelectedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveSelected, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(btnLoadClassRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnLoadClassRooms)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnAddAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddSelected)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemoveSelected)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Exam Duration Day Count");

        jLabel2.setText("Starting Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtDaysCount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDaysCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Enter Time Slots"));

        timeSlotsList.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(timeSlotsList);

        btnTimeslotAdd.setText("Add");
        btnTimeslotAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeslotAddActionPerformed(evt);
            }
        });

        btnRemoveTimeSlot.setText("Remove");
        btnRemoveTimeSlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveTimeSlotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnTimeslotAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveTimeSlot))
                    .addComponent(txtTimeSlotEnter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtTimeSlotEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveTimeSlot)
                    .addComponent(btnTimeslotAdd))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prgProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblProcessStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProcessStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prgProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshClassRooms(){
        selectedClassRoomsList.setModel(new DefaultListModel());
       
        DataBaseController dbc = DataBaseController.newInstance();
        classRooms = dbc.getClassRooms();
        DefaultListModel<ClassRoom> defaultModel = new DefaultListModel<>();
        System.out.println("called this method size :"+classRooms.size());
        for(int i =0;i<classRooms.size();i++){
            defaultModel.insertElementAt(classRooms.get(i), i);
            
        }
         classRoomsList.setModel(defaultModel);
    }
    
    private void btnLoadClassRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadClassRoomsActionPerformed
        // TODO add your handling code here:
        refreshClassRooms();
    }//GEN-LAST:event_btnLoadClassRoomsActionPerformed

    private void btnTimeslotAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeslotAddActionPerformed
        // TODO add your handling code here:
        if(!txtTimeSlotEnter.getText().equalsIgnoreCase("")){
            DefaultListModel dlm = (DefaultListModel) timeSlotsList.getModel();
            dlm.addElement(txtTimeSlotEnter.getText());
        }
    }//GEN-LAST:event_btnTimeslotAddActionPerformed

    private void btnRemoveTimeSlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveTimeSlotActionPerformed
        // TODO add your handling code here:
        if(timeSlotsList.getSelectedIndex()!=-1){
            ((DefaultListModel)timeSlotsList.getModel()).remove(timeSlotsList.getSelectedIndex());
        }
    }//GEN-LAST:event_btnRemoveTimeSlotActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        new InitiateProcess(lblProcessStatus,prgProcess).execute();
        
        /*
        List<String> timeSlots = new ArrayList<>();
        for(int i=0;i<timeSlotsList.getModel().getSize();i++){
            timeSlots.add(timeSlotsList.getModel().getElementAt(i));
        }
        
        int daysCount = Integer.parseInt(txtDaysCount.getText());
        Date startingDate = datePicker.getDate();
        System.out.println("Entered Time Slot"+timeSlots.size());
        String[] tempTimeSlotList = timeSlots.toArray(new String[timeSlots.size()]);
        
        TimeTableManager ttMan = TimeTableManager.getInstance();
        ttMan.setTimeSlotHeadings(tempTimeSlotList);
        
        ttMan.setClassRooms(classRooms);
        ttMan.setDates(startingDate,daysCount);
        /****************************************************************
        //here i have to call the setExams method of TimeTable Manager 
        //****************************************************************
        888888888988888888888888888888888888888888888888888888888888888888*/
        
        //Population pop = new Population(true,classRooms,tempTimeSlotList,daysCount,startingDate);
        /*
        Population pop = new Population(Algorithm.POPULATION_SIZE,true);
        for(int i=0;i<pop.size();i++){
            if(pop.getTimeTable(i)==null)System.out.println("Initial pop Time Table 1"+"null");
        }
        new Main(pop).setVisible(true);
        new ConstraintsManager().setVisible(true);*/
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        // TODO add your handling code here:
        
        DefaultListModel selectedListModel = ((DefaultListModel)selectedClassRoomsList.getModel());
        for(int index=0;index<((DefaultListModel)classRoomsList.getModel()).size();index++){
            ClassRoom cr = classRoomsList.getModel().getElementAt(index);
            if(!selectedListModel.contains(cr)) selectedListModel.addElement(cr);
        }
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveSelectedActionPerformed
        // TODO add your handling code here:
        DefaultListModel selectedListModel = ((DefaultListModel)selectedClassRoomsList.getModel());
        int[] indices = selectedClassRoomsList.getSelectedIndices();
        if(indices.length>0){
            selectedListModel.removeRange(indices[0], indices[indices.length-1]);
            
        }
    }//GEN-LAST:event_btnRemoveSelectedActionPerformed

    private void btnAddSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSelectedActionPerformed
        // TODO add your handling code here:
        DefaultListModel selectedListModel = ((DefaultListModel)selectedClassRoomsList.getModel());
        int[] indices = classRoomsList.getSelectedIndices();
        for(int index:indices){
            ClassRoom cr = classRoomsList.getModel().getElementAt(index);
            if(!selectedListModel.contains(cr))selectedListModel.addElement(cr);
        }
    }//GEN-LAST:event_btnAddSelectedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Initializing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Initializing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Initializing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initializing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Initializing().setVisible(true);
            }
        });
    }
    
    
    class InitiateProcess extends SwingWorker<Void,Void>{
        JLabel lblStatus;
        JProgressBar jBar;
        Population pop;
        boolean success =false;
        
        InitiateProcess(JLabel status,JProgressBar jBar){
            super();
            this.lblStatus = status;
            this.jBar = jBar;
            
        }
        
        @Override
        protected Void doInBackground()  {
            lblStatus.setForeground(Color.black);
            lblStatus.setText("Starting process...");
            lblStatus.setText("Adding TimeSlots...");
            jBar.setValue(10);
            List<String> timeSlots = new ArrayList<>();
            for(int i=0;i<timeSlotsList.getModel().getSize();i++){
                timeSlots.add(timeSlotsList.getModel().getElementAt(i));
            }
            
            lblStatus.setText("Updating Dates...");
            jBar.setValue(20);
            int daysCount = Integer.parseInt(txtDaysCount.getText());
            Date startingDate = datePicker.getDate();
            System.out.println("Entered Time Slot"+timeSlots.size());
            String[] tempTimeSlotList = timeSlots.toArray(new String[timeSlots.size()]);

            lblStatus.setText("Updating TimeSlots...");
            jBar.setValue(30);
            TimeTableManager ttMan = TimeTableManager.getInstance();
            ttMan.setTimeSlotHeadings(tempTimeSlotList);

            lblStatus.setText("Selecting ClassRooms...");
            jBar.setValue(40);
            ttMan.setClassRooms(classRooms);
            ttMan.setDates(startingDate,daysCount);
            /****************************************************************
            //here i have to call the setExams method of TimeTable Manager 
            //****************************************************************
            888888888988888888888888888888888888888888888888888888888888888888*/

            //Population pop = new Population(true,classRooms,tempTimeSlotList,daysCount,startingDate);
            lblStatus.setText("creating population...");
            try{
                pop = new Population(Algorithm.POPULATION_SIZE,true);
            }catch(NoBFSException ex){
                lblStatus.setText("No Posible Solution!!! ");
                lblStatus.setForeground(Color.red);
                jBar.setValue(0);
                return null;
            }
            
            jBar.setValue(90);
            for(int i=0;i<pop.size();i++){
                if(pop.getTimeTable(i)==null)System.out.println("Initial pop Time Table 1"+"null");
            }
            jBar.setValue(100);
            lblStatus.setText("Done initiating...");
            success =true;
            return null;
        }
        
        @Override
        public void done(){
            if(success){
                new Main(pop).setVisible(true);
                new ConstraintsManager().setVisible(true);
                jBar.setValue(0);
                
            }
            
            
        }
    
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnAddSelected;
    private javax.swing.JButton btnLoadClassRooms;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnRemoveSelected;
    private javax.swing.JButton btnRemoveTimeSlot;
    private javax.swing.JButton btnTimeslotAdd;
    private javax.swing.JList<ClassRoom> classRoomsList;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblProcessStatus;
    private javax.swing.JProgressBar prgProcess;
    private javax.swing.JList<ClassRoom> selectedClassRoomsList;
    private javax.swing.JList<String> timeSlotsList;
    private javax.swing.JTextField txtDaysCount;
    private javax.swing.JTextField txtTimeSlotEnter;
    // End of variables declaration//GEN-END:variables
}
